from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class my_resume(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    name=models.CharField(max_length=100)
    image=models.ImageField(upload_to='media')
    ability=models.CharField(max_length=100)
    dob=models.DateField()
    mobile=models.CharField(max_length=14)
    email=models.EmailField(max_length=250)
    github_id=models.CharField(max_length=250)
    linkedin_id=models.CharField(max_length=250)
    address=models.CharField(max_length=50)
    years_degree=models.CharField(max_length=15)
    name_degree=models.CharField(max_length=30)
    clg_name=models.CharField(max_length=100)
    year12th=models.CharField(max_length=15)
    class_name12th=models.CharField(max_length=10)
    school_name12th=models.CharField(max_length=100)
    year10th=models.CharField(max_length=15)
    class_name10th=models.CharField(max_length=10)
    school_name10th=models.CharField(max_length=100)
    language_1=models.CharField(max_length=50)
    percentage_1=models.CharField(max_length=70)
    para_1=models.CharField(max_length=500)
    working_years_1=models.CharField(max_length=50)
    company_name_1=models.CharField(max_length=50)
    designation_1=models.CharField(max_length=50)
    about_1=models.CharField(max_length=250)
    working_years_2=models.CharField(max_length=50)
    company_name_2=models.CharField(max_length=50)
    designation_2=models.CharField(max_length=50)
    about_2=models.CharField(max_length=250)
    skill_1=models.CharField(max_length=50)
    percent_1=models.CharField(max_length=30)
    interest_1=models.CharField(max_length=50)