# Generated by Django 4.2.4 on 2023-09-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('ability', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=250)),
                ('githubid', models.CharField(max_length=250)),
                ('linkedinid', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
                ('years_graduation', models.CharField(max_length=15)),
                ('name_degree', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=100)),
                ('year12th', models.CharField(max_length=15)),
                ('class_name12th', models.CharField(max_length=10)),
                ('school_name12th', models.CharField(max_length=100)),
                ('year10th', models.CharField(max_length=15)),
                ('class_name10th', models.CharField(max_length=10)),
                ('school_name10th', models.CharField(max_length=100)),
                ('language_1', models.CharField(max_length=50)),
                ('percentage_1', models.IntegerField()),
                ('language_2', models.CharField(max_length=50)),
                ('percentage_2', models.IntegerField()),
                ('para_1', models.CharField(max_length=500)),
                ('para_2', models.CharField(max_length=500)),
                ('working_years', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('working_years1', models.CharField(max_length=50)),
                ('company_name1', models.CharField(max_length=50)),
                ('designation1', models.CharField(max_length=50)),
                ('designation2', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=250)),
                ('skill_1', models.CharField(max_length=50)),
                ('percent_1', models.IntegerField()),
                ('skill_2', models.CharField(max_length=50)),
                ('percent_2', models.IntegerField()),
                ('skill_3', models.CharField(max_length=50)),
                ('percent_3', models.IntegerField()),
                ('skill_4', models.CharField(max_length=50)),
                ('percent_4', models.IntegerField()),
                ('skill_5', models.CharField(max_length=50)),
                ('percent_5', models.IntegerField()),
                ('skill_6', models.CharField(max_length=50)),
                ('percent_6', models.IntegerField()),
                ('interest_1', models.CharField(max_length=50)),
                ('interest_2', models.CharField(max_length=50)),
                ('interest_3', models.CharField(max_length=50)),
                ('interest_4', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='myprofile',
        ),
    ]
