# Generated by Django 4.2.4 on 2023-09-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_rename_mobile_my_resume_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_resume',
            old_name='about',
            new_name='about1',
        ),
        migrations.RemoveField(
            model_name='my_resume',
            name='interest_4',
        ),
        migrations.RemoveField(
            model_name='my_resume',
            name='percent_6',
        ),
        migrations.RemoveField(
            model_name='my_resume',
            name='skill_6',
        ),
        migrations.AddField(
            model_name='my_resume',
            name='about2',
            field=models.CharField(default=11, max_length=250),
            preserve_default=False,
        ),
    ]
