# Generated by Django 4.2.4 on 2023-09-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_rename_about1_my_resume_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_resume',
            old_name='about',
            new_name='about1',
        ),
        migrations.RenameField(
            model_name='my_resume',
            old_name='designation',
            new_name='designation1',
        ),
        migrations.RenameField(
            model_name='my_resume',
            old_name='interest',
            new_name='interest_1',
        ),
        migrations.RenameField(
            model_name='my_resume',
            old_name='language',
            new_name='language_1',
        ),
        migrations.RenameField(
            model_name='my_resume',
            old_name='para',
            new_name='para_1',
        ),
        migrations.RenameField(
            model_name='my_resume',
            old_name='percent',
            new_name='percent_1',
        ),
        migrations.RenameField(
            model_name='my_resume',
            old_name='percentage',
            new_name='percentage_1',
        ),
        migrations.RenameField(
            model_name='my_resume',
            old_name='skill',
            new_name='skill_1',
        ),
    ]
